#!/bin/sh
# Grimmory Spring Boot service

cd /app

exec s6-setuidgid bsd \
    /usr/local/bin/java \
    --enable-native-access=ALL-UNNAMED \
    --enable-preview \
    ${JAVA_OPTS} \
    -jar /app/app.jar
